### ISSUE TITLE
Adobe FDK autohint broken on MacOS 10.9.4

### ISSUE THREAD

**Issue by mundschenk-at** [zoltan-dulac/css3FontConverter#7]
A run with "autohint=adobe" failed to do any autohinting. A quick test with the command line parameters in the script gave this result:

`autohint -q -o foobar-Calendas_Plus.otf Calendas_Plus.otf 
Hinting font Calendas_Plus.otf. Start time: Mon Aug 18 23:32:15 2014.
Traceback (most recent call last):
  File "/Users/xxx/bin/FDK/Tools/osx/../SharedData/FDKScripts/autohint.py", line 1343, in <module>
    main()
  File "/Users/xxx/bin/FDK/Tools/osx/../SharedData/FDKScripts/autohint.py", line 1333, in main
    hintFile(options)
  File "/Users/xxx/bin/FDK/Tools/osx/../SharedData/FDKScripts/autohint.py", line 1073, in hintFile
    fdGlyphDict, fontDictList = fontData.getfdInfo(psName, path, options.allow_no_blues, options.noFlex, options.vCounterGlyphs, options.hCounterGlyphs, glyphList)
  File "/opt/local/libexec/FDK/Tools/SharedData/FDKScripts/BezTools.py", line 1345, in getfdInfo
    fdDict = self.getFontInfo(fontPSName, inputPath, allow_no_blues, noFlex, vCounterGlyphs, hCounterGlyphs, fdIndex)
  File "/opt/local/libexec/FDK/Tools/SharedData/FDKScripts/BezTools.py", line 1290, in getFontInfo
    raise   ACFontError("Error: font has neither StemSnapV nor StdVW!")
NameError: name 'ACFontError' is not defined
`

**Comment by zoltan-dulac** [comment]
Will not be fixing this, since the Adobe tool is not very easy to work with.
